AllCops:
  NewCops: enable

Metrics/MethodLength:
  Max: 50

Metrics/AbcSize:
  Max: 20

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Style/StringLiterals:
  Exclude:
    - 'Gemfile'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Exclude:
    - 'Gemfile'
    - 'Guardfile'
    - 'spec/**/*.rb'
